version: '3'

services:
  thunkable:
    container_name: thunkable
    build:
      context: .
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    restart: always
    ports:
      - 3005:3000
